### ISSUE TITLE
Ruby 3.0.0 Support

### ISSUE THREAD

**Issue by williamkennedy** [editmodelabs/editmode-rails#30]
Hey Guys,

Everything looks great. However, when I use Ruby3.0.1 it looks like it doesn't work. The error I get when I turn on log level normal is as follows:

```
wrong number of arguments (given 2, expected 1)
wrong number of arguments (given 2, expected 1): We can't render content for content_key
```

From a quick look, it looks like Ruby changed how it supports [keyword arguments](https://rubyreferences.github.io/rubychanges/3.0.html#language-changes).

I forked the Gem and quickly played around with it to validate this.

In lib/editmode/action_view_extensions/editmode_helper.rb, I simply changed the following line to see if this was the  case

```
chunk_value = Editmode::ChunkValue.new(identifier, options)
# changed to
chunk_value = Editmode::ChunkValue.new(identifier, **options)
```

This caused the content to render but naturally, a ton of tests broke.

I'm happy to help out on this but I'm stuck for time at the moment so I hope this helps out somewhat.

**Comment by notthatjen** [comment]
Hi @williamkennedy,
I've created a patch for this issue, you can now update your editmode gem version to `1.6.2`

Thanks for the heads up! 👍🏼

**Comment by williamkennedy** [comment]
Awesome. Can confirm new patch works as expected.

Glad I was able to help.
